export const GET_FOOD_INIT = 'GET_FOOD_INIT'
export const GET_FOOD_SUCCESS = 'GET_FOOD_SUCCESS'
export const GET_FOOD_ERROR = 'GET_FOOD_ERROR'

export const ORDER_REQUEST_INIT = 'ORDER_REQUEST_INIT'
export const ORDER_REQUEST_SUCCESS = 'ORDER_REQUEST_SUCCESS'
export const ORDER_REQUEST_ERROR = 'ORDER_REQUEST_ERROR'